image: maven:3.3.9

pipelines:
  default:
    - step:
        name: Test and build
        caches:
          - maven
        script:
          - mvn clean package
        artifacts:
          - target/**